"""add comment.confirm

Revision ID: 8f81ea1b70fe
Revises: 
Create Date: 2017-01-03 08:46:35.508217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f81ea1b70fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('confirm', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'confirm')
    ### end Alembic commands ###
